<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="44" left="499" height="811" width="941"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="gcross.20100107191635.1408"><vh>@chapters</vh></v>
<v t="gcross.20100107191635.1409"><vh>@thin test-framework-antitest.cabal</vh></v>
<v t="gcross.20100107191635.1411"><vh>@thin Setup.hs</vh></v>
<v t="gcross.20100107191635.1793"><vh>@thin sources/Test/Framework/Providers/AntiTest.hs</vh></v>
<v t="gcross.20100107191635.1519"><vh>@thin tests/test.hs</vh></v>
</vnodes>
<tnodes>
<t tx="gcross.20100107191635.1408" str_leo_pos="1"></t>
</tnodes>
</leo_file>
